plugins:
  thumbnail_toggle_enabled:
    client: true
    default: true
  thumbnail_toggle_category_override:
    client: true
    default: true
    description: "Allow category settings to override global thumbnail display settings"
  thumbnail_toggle_default:
    client: true
    default: true
    description: "Default state for thumbnails (show or hide)" 